lst = list()
lst[[length(lst)+1]] = class(gtkHBoxNew())
lst[[length(lst)+1]] = class(gtkButtonNewFromStock("gtk-ok"))
lst[[length(lst)+1]] = class(gtkButtonNewWithLabel("fred"))
lst[[length(lst)+1]] = class(gtkImageNew())
lst[[length(lst)+1]] = class(gtkWindowNew(show=FALSE))
lst[[length(lst)+1]] = class(gtkCalendarNew())
lst[[length(lst)+1]] = class(gtkCheckButtonNewWithLabel("fred"))
lst[[length(lst)+1]] = class(gtkTreeStoreNew("gchararray"))
lst[[length(lst)+1]] = class(gtkComboBoxEntryNewWithModel(rGtkDataFrame(mtcars), 0))
lst[[length(lst)+1]] = class(gtkComboBoxNewWithModel(rGtkDataFrame(mtcars),0))
lst[[length(lst)+1]] = class(gtkCellRendererTextNew())
lst[[length(lst)+1]] = class(gtkEntryNew())
lst[[length(lst)+1]] = class(gtkEntryCompletionNew())
lst[[length(lst)+1]] = class(gtkExpanderNew())
lst[[length(lst)+1]] = class(gtkFrameNew())
lst[[length(lst)+1]] = class(gtkLabelNew())
lst[[length(lst)+1]] = class(gtkDrawingAreaNew())
lst[[length(lst)+1]] = class(gtkScrolledWindowNew())
lst[[length(lst)+1]] = class(gtkCellRendererPixbufNew())
lst[[length(lst)+1]] = class(gtkTreeViewColumnNew())
lst[[length(lst)+1]] = class(gtkCellRendererTextNew())
lst[[length(lst)+1]] = class(gtkHBoxNew(spacing=0))
lst[[length(lst)+1]] = class(gtkVBoxNew(spacing=0))
lst[[length(lst)+1]] = class(gtkImageNew())
lst[[length(lst)+1]] = class(gtkEventBoxNew())
lst[[length(lst)+1]] = class(gtkLabelNew())
lst[[length(lst)+1]] = class(gtkTableNew(1, 1, homogeneous=TRUE))
lst[[length(lst)+1]] = class(gtkMenuNew())
lst[[length(lst)+1]] = class(gtkMenuBarNew())
lst[[length(lst)+1]] = class(gtkImageNew())
lst[[length(lst)+1]] = class(gtkNotebookNew())
lst[[length(lst)+1]] = class(gtkHPanedNew())
lst[[length(lst)+1]] = class(gtkVPanedNew())
lst[[length(lst)+1]] = class(gtkRadioButtonNewWithLabel(NULL, "fred"))
lst[[length(lst)+1]] = class(gtkHSeparatorNew())
lst[[length(lst)+1]] = class(gtkVSeparatorNew())
lst[[length(lst)+1]] = class(gtkHScaleNewWithRange(0, 1, .1))
lst[[length(lst)+1]] = class(gtkVScaleNewWithRange(0, 1, .1))
lst[[length(lst)+1]] = class(gtkAdjustmentNew(0, 1, .1))
lst[[length(lst)+1]] = class(gtkSpinButtonNew())
lst[[length(lst)+1]] = class(gtkStatusbarNew())
lst[[length(lst)+1]] = class(gtkTextViewNew())
lst[[length(lst)+1]] = class(gtkActionGroupNew(name="ActionGroup"))
lst[[length(lst)+1]] = class(gtkUIManagerNew())
lst[[length(lst)+1]] = class(gtkIconFactoryNew())
lst[[length(lst)+1]] = class(gtkIconSourceNew())
lst[[length(lst)+1]] = class(gtkIconSetNew())

print(lst)


newlst = list()
for(i in 1:length(lst))
  newlst[[i]] = rev(lst[[i]])

setOldClassValues = unlist(newlst)
setIslst = list()
for(i in 1:length(newlst)) {
  for(j in 1:(length(newlst[[i]])-1)) {
    tmp = newlst[[i]]
    key = paste(tmp[j],".",tmp[j+1], collapse="",sep="")
    setIslst[[key]] = c(tmp[j],tmp[j+1])
  }
}

print(unique(setOldClassValues))
cat("\n\n")
for(i in 1:length(setIslst)) {
  tmp = setIslst[[i]]
  cat(paste("setIs('",tmp[1],"','",tmp[2],"')", sep="",collapse=""),"\n")
}
